name: Job search & email

on:
  schedule:
    - cron: '30 3 * * *'   # 09:00 IST -> 03:30 UTC
    - cron: '30 6 * * *'   # 12:00 IST -> 06:30 UTC
    - cron: '30 12 * * *'  # 18:00 IST -> 12:30 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run job search
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python search_and_email.py
